"""
AlgoSkill Benchmark Problem Set
20 classic algorithmic problems with test cases.
"""

PROBLEMS = [
    {
        "id": "P01",
        "name": "Two Sum",
        "difficulty": "easy",
        "category": "array_hashing",
        "description": """Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. Assume exactly one solution exists. Do not use the same element twice.""",
        "constraints": "2 <= nums.length <= 10^4, -10^9 <= nums[i] <= 10^9, -10^9 <= target <= 10^9",
        "function_signature": "def solution(nums, target):",
        "tests": [
            (([2, 7, 11, 15], 9), [0, 1]),
            (([3, 2, 4], 6), [1, 2]),
            (([3, 3], 6), [0, 1]),
            (([1, 2, 3, 4, 5], 9), [3, 4]),
            (([0, 4, 3, 0], 0), [0, 3]),
        ],
        "check": "sorted",
    },
    {
        "id": "P02",
        "name": "Longest Common Subsequence",
        "difficulty": "medium",
        "category": "dp",
        "description": """Given two strings text1 and text2, return the length of their longest common subsequence. A subsequence is derived by deleting some characters without changing order.""",
        "constraints": "1 <= text1.length, text2.length <= 1000, strings consist of lowercase English letters",
        "function_signature": "def solution(text1, text2):",
        "tests": [
            (("abcde", "ace"), 3),
            (("abc", "abc"), 3),
            (("abc", "def"), 0),
            (("bsbininm", "jmjkbkjkv"), 1),
            (("oxcpqrsvwf", "shmtulqrypy"), 2),
            (("aaaaaa", "aaaa"), 4),
        ],
        "check": "exact",
    },
    {
        "id": "P03",
        "name": "Coin Change",
        "difficulty": "medium",
        "category": "dp",
        "description": """You have coins of given denominations. Return the fewest coins needed to make up the amount. If impossible return -1.""",
        "constraints": "1 <= coins.length <= 12, 1 <= coins[i] <= 2^31-1, 0 <= amount <= 10^4",
        "function_signature": "def solution(coins, amount):",
        "tests": [
            (([1, 5, 11], 15), 3),
            (([2], 3), -1),
            (([1], 0), 0),
            (([1, 2, 5], 11), 3),
            (([186, 419, 83, 408], 6249), 20),
            (([1, 5, 10, 25], 41), 4),
        ],
        "check": "exact",
    },
    {
        "id": "P04",
        "name": "Number of Islands",
        "difficulty": "medium",
        "category": "graph_bfs",
        "description": """Given an m x n 2D binary grid of '1' (land) and '0' (water), return the number of islands. An island is surrounded by water and formed by connecting adjacent land cells horizontally or vertically.""",
        "constraints": "1 <= m,n <= 300, grid[i][j] is '0' or '1'",
        "function_signature": "def solution(grid):",
        "tests": [
            (([["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]],), 1),
            (([["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]],), 3),
            (([["1"]],), 1),
            (([["0"]],), 0),
            (([["1","0"],["0","1"]],), 2),
        ],
        "check": "exact",
    },
    {
        "id": "P05",
        "name": "Jump Game II",
        "difficulty": "medium",
        "category": "greedy",
        "description": """You are given 0-indexed array nums. You start at index 0. nums[i] is the maximum jump length from i. Return the minimum number of jumps to reach the last index.""",
        "constraints": "1 <= nums.length <= 10^4, 0 <= nums[i] <= 1000, test cases guarantee you can reach the last index",
        "function_signature": "def solution(nums):",
        "tests": [
            (([2, 3, 1, 1, 4],), 2),
            (([2, 3, 0, 1, 4],), 2),
            (([1],), 0),
            (([1, 2],), 1),
            (([2, 1, 2, 1, 0, 2],), 3),
            (([5, 9, 3, 2, 1, 0, 2, 3, 3, 1, 0, 0],), 3),
        ],
        "check": "exact",
    },
    {
        "id": "P06",
        "name": "Meeting Rooms II",
        "difficulty": "medium",
        "category": "interval_heap",
        "description": """Given an array of meeting time intervals where intervals[i] = [starti, endi], return the minimum number of conference rooms required.""",
        "constraints": "1 <= intervals.length <= 10^4, 0 <= starti < endi <= 10^6",
        "function_signature": "def solution(intervals):",
        "tests": [
            (([[0,30],[5,10],[15,20]],), 2),
            (([[7,10],[2,4]],), 1),
            (([[1,5],[2,6],[3,7]],), 3),
            (([[0,5],[5,10]],), 1),
            (([[1,4],[2,5],[7,9]],), 2),
            (([[6,17],[8,9],[11,12],[6,9],[6,8]],), 4),
        ],
        "check": "exact",
    },
    {
        "id": "P07",
        "name": "Trapping Rain Water",
        "difficulty": "hard",
        "category": "two_pointer_stack",
        "description": """Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.""",
        "constraints": "n == height.length, 1 <= n <= 2*10^4, 0 <= height[i] <= 10^5",
        "function_signature": "def solution(height):",
        "tests": [
            (([0,1,0,2,1,0,1,3,2,1,2,1],), 6),
            (([4,2,0,3,2,5],), 9),
            (([1],), 0),
            (([1,2],), 0),
            (([3,0,2,0,4],), 7),
            (([4,2,3],), 1),
        ],
        "check": "exact",
    },
    {
        "id": "P08",
        "name": "Minimum Window Substring",
        "difficulty": "hard",
        "category": "sliding_window",
        "description": """Given strings s and t, return the minimum window substring of s that contains all characters in t. If no such window exists, return "".""",
        "constraints": "1 <= m, n <= 10^5, s and t consist of uppercase and lowercase English letters",
        "function_signature": "def solution(s, t):",
        "tests": [
            (("ADOBECODEBANC", "ABC"), "BANC"),
            (("a", "a"), "a"),
            (("a", "aa"), ""),
            (("abc", "b"), "b"),
            (("cabwefgewcwaefgcf", "cae"), "cwae"),
        ],
        "check": "exact",
    },
    {
        "id": "P09",
        "name": "Course Schedule",
        "difficulty": "medium",
        "category": "graph_topo",
        "description": """There are numCourses labeled 0 to numCourses-1. prerequisites[i] = [ai, bi] means to take ai you must first take bi. Return true if possible to finish all courses.""",
        "constraints": "1 <= numCourses <= 2000, 0 <= prerequisites.length <= 5000, no duplicate prerequisites",
        "function_signature": "def solution(numCourses, prerequisites):",
        "tests": [
            ((2, [[1,0]]), True),
            ((2, [[1,0],[0,1]]), False),
            ((1, []), True),
            ((4, [[1,0],[2,0],[3,1],[3,2]]), True),
            ((3, [[1,0],[1,2],[0,1]]), False),
        ],
        "check": "exact",
    },
    {
        "id": "P10",
        "name": "Word Break",
        "difficulty": "medium",
        "category": "dp_string",
        "description": """Given a string s and dictionary wordDict, return true if s can be segmented into space-separated words from the dictionary.""",
        "constraints": "1 <= s.length <= 300, 1 <= wordDict.length <= 1000, 1 <= wordDict[i].length <= 20",
        "function_signature": "def solution(s, wordDict):",
        "tests": [
            (("leetcode", ["leet", "code"]), True),
            (("applepenapple", ["apple", "pen"]), True),
            (("catsandog", ["cats", "dog", "sand", "and", "cat"]), False),
            (("bb", ["a", "b", "bbb", "bbbb"]), True),
            (("aaaaaaa", ["aaaa", "aaa"]), True),
            (("abcd", ["a", "abc", "b", "cd"]), True),
        ],
        "check": "exact",
    },
    {
        "id": "P11",
        "name": "Edit Distance",
        "difficulty": "hard",
        "category": "dp_string",
        "description": """Given two strings word1 and word2, return the minimum number of operations (insert, delete, replace) required to convert word1 to word2.""",
        "constraints": "0 <= word1.length, word2.length <= 500, consist of lowercase English letters",
        "function_signature": "def solution(word1, word2):",
        "tests": [
            (("horse", "ros"), 3),
            (("intention", "execution"), 5),
            (("", ""), 0),
            (("", "abc"), 3),
            (("abc", ""), 3),
            (("abc", "abc"), 0),
            (("abcdef", "azced"), 3),
        ],
        "check": "exact",
    },
    {
        "id": "P12",
        "name": "Largest Rectangle in Histogram",
        "difficulty": "hard",
        "category": "monotone_stack",
        "description": """Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.""",
        "constraints": "1 <= heights.length <= 10^5, 0 <= heights[i] <= 10^4",
        "function_signature": "def solution(heights):",
        "tests": [
            (([2,1,5,6,2,3],), 10),
            (([2,4],), 4),
            (([1],), 1),
            (([0],), 0),
            (([6,2,5,4,5,1,6],), 12),
            (([2,1,2],), 3),
        ],
        "check": "exact",
    },
    {
        "id": "P13",
        "name": "Sliding Window Maximum",
        "difficulty": "hard",
        "category": "deque",
        "description": """You are given an integer array nums and an integer k. Return the max sliding window — the max value in each window of size k as it slides from left to right.""",
        "constraints": "1 <= nums.length <= 10^5, -10^4 <= nums[i] <= 10^4, 1 <= k <= nums.length",
        "function_signature": "def solution(nums, k):",
        "tests": [
            (([1,3,-1,-3,5,3,6,7], 3), [3,3,5,5,6,7]),
            (([1], 1), [1]),
            (([1,-1], 1), [1,-1]),
            (([9,11], 2), [11]),
            (([4,-2], 2), [4]),
            (([2,1,5,3,6,4,8,9], 3), [5,5,6,6,8,9]),
        ],
        "check": "exact",
    },
    {
        "id": "P14",
        "name": "Maximal Square",
        "difficulty": "medium",
        "category": "dp_2d",
        "description": """Given an m x n binary matrix filled with '0's and '1's, find the largest square containing only '1's and return its area.""",
        "constraints": "m == matrix.length, n == matrix[i].length, 1 <= m, n <= 300",
        "function_signature": "def solution(matrix):",
        "tests": [
            (([["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]],), 4),
            (([["0","1"],["1","0"]],), 1),
            (([["0"]],), 0),
            (([["1","1","1"],["1","1","1"],["1","1","1"]],), 9),
            (([["1","0"],["0","1"]],), 1),
        ],
        "check": "exact",
    },
    {
        "id": "P15",
        "name": "Minimum Cost to Connect Points",
        "difficulty": "medium",
        "category": "mst_greedy",
        "description": """You are given an array points of [xi, yi] on the XY-plane. The cost of connecting two points is the Manhattan distance. Return the minimum cost to connect all points (MST).""",
        "constraints": "1 <= points.length <= 1000, -10^6 <= xi, yi <= 10^6, all pairs are distinct",
        "function_signature": "def solution(points):",
        "tests": [
            (([[0,0],[2,2],[3,10],[5,2],[7,0]],), 20),
            (([[3,12],[-2,5],[-4,1]],), 18),
            (([[0,0],[1,1],[1,0],[-1,1]],), 4),
            (([[0,0]],), 0),
            (([[-1000000,-1000000],[1000000,1000000]],), 4000000),
        ],
        "check": "exact",
    },
    {
        "id": "P16",
        "name": "Longest Increasing Subsequence",
        "difficulty": "medium",
        "category": "dp_binary_search",
        "description": """Given integer array nums, return the length of the longest strictly increasing subsequence.""",
        "constraints": "1 <= nums.length <= 2500, -10^4 <= nums[i] <= 10^4",
        "function_signature": "def solution(nums):",
        "tests": [
            (([10,9,2,5,3,7,101,18],), 4),
            (([0,1,0,3,2,3],), 4),
            (([7,7,7,7,7,7,7],), 1),
            (([1],), 1),
            (([4,10,4,3,8,9],), 3),
            (([3,5,6,2,5,4,19,5,6,7,12],), 6),
        ],
        "check": "exact",
    },
    {
        "id": "P17",
        "name": "K Closest Points to Origin",
        "difficulty": "medium",
        "category": "heap",
        "description": """Given an array of points on the X-Y plane and integer k, return the k closest points to the origin (0,0). Distance is Euclidean. The answer can be in any order.""",
        "constraints": "1 <= k <= points.length <= 10^4, -10^4 <= xi, yi <= 10^4",
        "function_signature": "def solution(points, k):",
        "tests": [
            (([[1,3],[-2,2]], 1), [[-2,2]]),
            (([[3,3],[5,-1],[-2,4]], 2), [[3,3],[-2,4]]),
            (([[0,1],[1,0]], 2), [[0,1],[1,0]]),
            (([[1,1],[2,2],[3,3]], 1), [[1,1]]),
        ],
        "check": "sorted_lists",
    },
    {
        "id": "P18",
        "name": "Find Peak Element",
        "difficulty": "medium",
        "category": "binary_search",
        "description": """A peak element is greater than its neighbors. Given integer array nums, find a peak element and return its index. Assume nums[-1] = nums[n] = -inf. Must run in O(log n) time.""",
        "constraints": "1 <= nums.length <= 1000, -2^31 <= nums[i] <= 2^31-1, nums[i] != nums[i+1]",
        "function_signature": "def solution(nums):",
        "tests": [
            (([1,2,3,1],), 2),
            (([1,2,1,3,5,6,4],), 5),
            (([1],), 0),
            (([2,1],), 0),
            (([1,2],), 1),
        ],
        "check": "peak_valid",
    },
    {
        "id": "P19",
        "name": "Subsets",
        "difficulty": "medium",
        "category": "backtracking_bitmask",
        "description": """Given an integer array nums of unique elements, return all possible subsets (power set). The solution set must not contain duplicate subsets. Return in any order.""",
        "constraints": "1 <= nums.length <= 10, -10 <= nums[i] <= 10, all nums are unique",
        "function_signature": "def solution(nums):",
        "tests": [
            (([1,2,3],), sorted([sorted(s) for s in [[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]])),
            (([0],), [[], [0]]),
        ],
        "check": "subset_valid",
    },
    {
        "id": "P20",
        "name": "Regular Expression Matching",
        "difficulty": "hard",
        "category": "dp_hard",
        "description": """Given input string s and pattern p, implement regular expression matching with '.' (matches any single character) and '*' (matches zero or more of preceding element). The matching should cover the entire string.""",
        "constraints": "1 <= s.length <= 20, 1 <= p.length <= 20, s contains only lowercase letters, p contains lowercase letters, '.', '*'",
        "function_signature": "def solution(s, p):",
        "tests": [
            (("aa", "a"), False),
            (("aa", "a*"), True),
            (("ab", ".*"), True),
            (("aab", "c*a*b"), True),
            (("mississippi", "mis*is*p*."), False),
            (("", "a*"), True),
            (("aaa", "a*a"), True),
        ],
        "check": "exact",
    },
]


def get_problems_by_difficulty(difficulty=None):
    if difficulty is None:
        return PROBLEMS
    return [p for p in PROBLEMS if p["difficulty"] == difficulty]


def get_problem_by_id(pid):
    for p in PROBLEMS:
        if p["id"] == pid:
            return p
    return None
